### ISSUE TITLE
زوی IP کثیف کار میکنه؟

### ISSUE THREAD

**Issue by nsa14** [ReturnFI/Port-Shifter#1]
سلام 
تشکر میکنم از اسکریپت خوبی ک نوشتین

میخاستم بدونم کدوم روش تانل این اسکریپت روی سرور با IP کثیف کار میکنه؟

**Comment by ReturnFI** [comment]
درود
خواهش میکنم لطف دارید.
اگر سرو خارجتون IP تمیز نداره
میتونید از روشی IPv6 لوکال با این [آموزش ](https://hiddify.com/fa/manager/domain-worker-cdn-and-tunneling/Tutorial-for-setting-up-local-IPv6/) استفاده کنید و از تانل dokodemo-door استفاده کنید
