### ISSUE TITLE
حذف شدن رول‌های آی پی تیبل بعد از ری استارت

### ISSUE THREAD

**Issue by madar54** [ReturnFI/Port-Shifter#3]
با سلام زمانی که از آی پی شیفتر استفاده می‌شود و از گزینه آی پی تیبل استفاده می‌شود بعد از ری استارت سرور پورت‌ها در آی پی تیبل حذف می‌گردند دلیل آن چیست و راهنمایی بفرمایید

**Comment by ReturnFI** [comment]
سلام بعد از نصب و استفاده و قبل از ریبوت چک کنید رول ها داخل فایل `rules.v4` ذخیره میشن یا خیر؟
با ادیتور `nano` باز کنید
`nano /etc/iptables/rules.v4`
