### ISSUE TITLE
هدر

### ISSUE THREAD

**Issue by mohsendeldari123** [ReturnFI/Port-Shifter#4]
سلام و عرض ادب چرا هدر میزاریم کار نمیکنه اما بدون هدر کار میکنه

**Comment by ReturnFI** [comment]
سلام .
داخل پورت شیفتر هدر نداریم
اگر با کانفیگ هدر دار مشکل دارین دقیق تر بگید تا بررسی کنم.

**Comment by mohsendeldari123** [comment]
> بگید

بنده پنل سنایی دارم همه کلایناتم کانفیگاشون هدر داره الان با اسکریپ شما میزنم چون کانفیگ هدر داره جواب نمیده حتما باید کانفیگ بدون هدر باشه ک  کار کنه

**Comment by ReturnFI** [comment]
ببینید ساختار پورت فوروارد این هستش  که دیتا رو از یک پورت و سرور به پورت و سرور دیگر منتقل میکنه کاری به نوع کانفیگ نداره

من تست با کانفیگ هدر دار و بدون هدر انجام  دادم و موردی نیست.
از فایروال و پورت ها مطمئن بشید

**Comment by ReturnFI** [comment]
از هر چهار روش تست بگیرید.
نوع کانفیگ شما برای تانل زدن با اسکریپت پورت شیفتر مهم نیست.

**Comment by mohsendeldari123** [comment]
هر چهار کانفیگم امتحان گردم ام نشد اگه ممکنه بیاد تلگرام من دوتا سرور بدم خودتون کانفیگ کنید

**Comment by mohsendeldari123** [comment]
> از هر چهار روش تست بگیرید. نوع کانفیگ شما برای تانل زدن با اسکریپت پورت شیفتر مهم نیست.

من امروز با دوتا سرور دگ هم امتحان کردم بدون هدر کار میکنه اما هدر میزارم کار نمیکنه کاش اینو بررسی کنید درست شه واقعا این اسکریپ عالیه اگه این یه موضوع هم درست شه
